# Basic configuration
CONFIG_ZMK_SLEEP=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Split keyboard settings - explicitly set as peripheral
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Name (can be different to identify during troubleshooting)
CONFIG_ZMK_KEYBOARD_NAME="Wizkey Right"

# HID configuration - make sure USB works
CONFIG_ZMK_USB=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
