# Disable sleep since we're using USB power
CONFIG_ZMK_SLEEP=n

# Disable Bluetooth
CONFIG_BT=n
CONFIG_ZMK_BLE=n

# Enable USB
CONFIG_ZMK_USB=y
CONFIG_USB_DEVICE_STACK=y

# Enable split USB
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_USB=y

# Name
CONFIG_ZMK_KEYBOARD_NAME="Wizkey"

# HID reports
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
